const menu = [
  {
    id: 1,
    title: "paneer 65",
    category: "veg",
    price: 160,
    img: "./item-1.jpeg",
    desc: `Spicy and crispy paneer (cottage cheese) dish, flavored with aromatic spices and served as an appetizer.`,
  },
  {
    id: 2,
    title: "chilly paneer",
    category: "veg",
    price: 160,
    img: "./item-2.jpeg",
    desc: `Indo-Chinese dish made with paneer (cottage cheese), bell peppers, and onions, tossed in a spicy and tangy sauce.`,
  },
  {
    id: 3,
    title: "veg 65",
    category: "veg",
    price: 160,
    img: "./item-3.jpeg",
    desc: `Spicy and crispy vegetarian dish inspired by the famous Chicken 65, made with a flavorful blend of spices.`,
  },
  {
    id: 4,
    title: "gobi machuria",
    category: "veg",
    price: 20.99,
    img: "./item-4.jpeg",
    desc: `Crispy and tangy cauliflower dish, with a perfect balance of sweet, spicy, and sour flavors.`,
  },
  {
    id: 5,
    title: "gobi 65",
    category: "veg",
    price: 150,
    img: "./item-5.jpeg",
    desc: `Spicy and crispy cauliflower dish, marinated with flavorful spices and deep-fried to perfection.`,
  },
  {
    id: 6,
    title: "aloo 65",
    category: "veg",
    price: 150,
    img: "./images/item-6.jpeg",
    desc: `Spicy and crispy potato dish, similar to the popular Chicken 65, but made with potatoes.`,
  },
  {
    id: 7,
    title: "paneer manchuria",
    category: "veg",
    price: 160,
    img: "./images/item-7.jpeg",
    desc: `Indo-Chinese dish made with paneer (cottage cheese) cooked in a tangy and flavorful sauce.`,
  },
  {
    id: 8,
    title: "veg manchuria",
    category: "veg",
    price: 150,
    img: "./images/item-8.jpeg",
    desc: `Indo-Chinese dish made with mixed vegetables cooked in a spicy and tangy sauce.`,
  },
  {
    id: 9,
    title: "veg spring roll",
    category: "veg",
    price: 150,
    img: "./images/item-9.jpeg",
    desc: `Crispy and flavorful appetizer made with a filling of mixed vegetables wrapped in a thin spring roll pastry.`,
  },
  {
    id: 10,
    title: "paneer spring roll",
    category: "veg",
    price: 160,
    img: "./images/item-10.jpeg",
    desc: `Delicious appetizer made with a filling of paneer (cottage cheese) and mixed vegetables wrapped in a spring roll pastry.`,
  },
  {
    id: 11,
    title: "crispy veg",
    category: "veg",
    price: 120,
    img: "./images/item-11.jpeg",
    desc: `Crispy and flavorful vegetarian dish made with a variety of vegetables, coated in a light batter and deep-fried.`,
  },
  {
    id: 12,
    title: "veg bullet",
    category: "veg",
    price: 120,
    img: "./images/item-12.jpeg",
    desc: `A popular vegetarian snack made with a mixture of mashed potatoes, spices, and breadcrumbs, shaped into bullet-like rolls and deep-fried until golden and crispy.`,
  },
  {
    id: 13,
    title: "onion pakoda",
    category: "veg",
    price: 120,
    img: "./images/item-13.jpg",
    desc: `Crispy and flavorful fritters made with sliced onions, gram flour, and spices, perfect as a tea-time snack.`,
  },
  {
    id: 14,
    title: "veg pakoda",
    category: "veg",
    price: 120,
    img: "./images/item-14.jpeg",
    desc: `Assorted mixed vegetable fritters, made with a batter of gram flour and spices, served hot and crispy.`,
  },
  {
    id: 15,
    title: "green peas",
    category: "veg",
    price: 120,
    img: "./images/item-15.jpg",
    desc: `Delicious and comforting dish made with green peas cooked in a spiced tomato-based gravy.`,
  },
  {
    id: 16,
    title: "special green peas",
    category: "veg",
    price: 140,
    img: "./images/item-16.jpg",
    desc: `Exquisite preparation of green peas cooked with special spices, herbs, and a creamy sauce.`,
  },
  {
    id: 17,
    title: "finger chips",
    category: "veg",
    price: 130,
    img: "./images/item-17.jpeg",
    desc: `Classic dish of crispy and golden french fries, perfect as a snack or side dish.`,
  },
  {
    id: 18,
    title: "veg cutlet",
    category: "veg",
    price: 160,
    img: "./images/item-18.jpeg",
    desc: `Tasty and crispy cutlets made with a mix of mashed vegetables, spices, and breadcrumbs, served hot.`,
  },
  {
    id: 19,
    title: "corn fry",
    category: "veg",
    price: 120,
    img: "./images/item-19.png",
    desc: `Delicious and flavorful dish made with fried corn kernels, seasoned with spices and herbs.`,
  },
  {
    id: 20,
    title: "crispy corn",
    category: "veg",
    price: 170,
    img: "./images/item-20.png",
    desc: `Crispy and crunchy corn dish, coated with a flavorful seasoning and fried until golden brown.`,
  },
  {
    id: 21,
    title: "masala papad",
    category: "veg",
    price: 28,
    img: "./images/item-21.png",
    desc: `Crispy papad topped with a tangy and spicy mixture of onions, tomatoes, and spices, served as an appetizer.`,
  },
  {
    id: 22,
    title: "roast papad",
    category: "veg",
    price: 22,
    img: "./images/item-22.png",
    desc: `Roasted papad served as a crunchy and savory accompaniment to meals, perfect for adding a touch of crispiness.`,
  },
  {
    id: 23,
    title: "green salad",
    category: "veg",
    price: 45,
    img: "./images/item-23.png",
    desc: `A refreshing and nutritious salad made with a variety of fresh green vegetables, perfect for a healthy meal.`,
  },
  {
    id: 24,
    title: "chicken masala",
    category: "chicken",
    price: 200,
    img: "./images/item-24.png",
    desc: `Delicious chicken cooked in a flavorful masala sauce.`,
  },  
  {
    id: 25,
    title: "chicken palak",
    category: "chicken",
    price: 200,
    img: "./images/item-25.png",
    desc: `Tender chicken cooked with spinach in a delectable blend of spices.`,
  },
  {
    id: 26,
    title: "punjabi chicken",
    category: "chicken",
    price: 200,
    img: "./images/item-26.png",
    desc: `Traditional Punjabi-style chicken curry with rich and aromatic flavors.`,
  },
  {
    id: 27,
    title: "special chicken",
    category: "chicken",
    price: 200,
    img: "./images/item-27.png",
    desc: `A special chicken dish prepared with a unique blend of spices.`,
  },
  {
    id: 28,
    title: "chicken tikka butter masala",
    category: "chicken",
    price: 200,
    img: "./images/item-28.png",
    desc: `Tender chicken tikka cooked in a creamy and buttery tomato-based sauce.`,
  },
  {
    id: 29,
    title: "butter chicken boneless",
    category: "chicken",
    price: 200,
    img: "./images/item-29.png",
    desc: `Boneless chicken cooked in a rich and creamy butter sauce.`,
  },
  {
    id: 30,
    title: "butter chicken with bones",
    category: "chicken",
    price: 200,
    img: "./images/item-30.png",
    desc: `Chicken with bones cooked in a luscious and flavorful butter sauce.`,
  },
  {
    id: 31,
    title: "ginger chicken boneless",
    category: "chicken",
    price: 200,
    img: "./images/item-31.png",
    desc: `Boneless chicken cooked with ginger and spices for a delicious flavor.`,
  },
  {
    id: 32,
    title: "ginger chicken with bones",
    category: "chicken",
    price: 200,
    img: "./images/item-32.png",
    desc: `Chicken with bones cooked with ginger and spices for a delightful taste.`,
  },
  {
    id: 33,
    title: "chicken gravy",
    category: "chicken",
    price: 200,
    img: "./images/item-33.png",
    desc: `Tender and succulent chicken cooked in a flavorful and savory gravy.`,
  },
  {
    id: 34,
    title: "mutton punjabi",
    category: "mutton",
    price: 200,
    img: "./images/item-34.png",
    desc: `Traditional Punjabi-style mutton curry with rich and aromatic flavors.`,
  },
  {
    id: 35,
    title: "mutton masala",
    category: "mutton",
    price: 200,
    img: "./images/item-35.png",
    desc: `Tender mutton cooked in a flavorful masala sauce.`,
  },
  {
    id: 36,
    title: "mutton saag",
    category: "mutton",
    price: 200,
    img: "./images/item-36.png",
    desc: `Succulent mutton cooked with spinach in a delectable blend of spices.`,
  },
  {
    id: 37,
    title: "special mutton",
    category: "mutton",
    price: 200,
    img: "./images/item-37.png",
    desc: `A special mutton dish prepared with a unique blend of spices.`,
  },
  {
    id: 38,
    title: "ginger mutton",
    category: "mutton",
    price: 200,
    img: "./images/item-38.png",
    desc: `Mutton cooked with ginger and spices for a delicious flavor.`,
  },
  {
    id: 39,
    title: "keema mutton",
    category: "mutton",
    price: 200,
    img: "./images/item-39.png",
    desc: `Minced mutton cooked to perfection with a medley of spices.`,
  },
  {
    id: 40,
    title: "nargis kofta fry",
    category: "mutton",
    price: 200,
    img: "./images/item-40.png",
    desc: `Fried mutton kofta balls made with a flavorful stuffing.`,
  },
  {
    id: 41,
    title: "keema fry",
    category: "mutton",
    price: 200,
    img: "./images/item-41.png",
    desc: `Spicy and aromatic fried minced mutton dish.`,
  },
  {
    id: 42,
    title: "keema masala fry",
    category: "mutton",
    price: 200,
    img: "./images/item-42.png",
    desc: `Fried minced mutton cooked in a rich and spicy masala.`,
  },
  {
    id: 43,
    title: "kidney masala",
    category: "mutton",
    price: 200,
    img: "./images/item-43.png",
    desc: `Savory and spicy kidney masala made with tender mutton kidneys.`,
  },
  {
    id: 44,
    title: "kidney roast",
    category: "mutton",
    price: 200,
    img: "./images/item-44.png",
    desc: `Roasted mutton kidneys with aromatic spices and flavors.`,
  },
  {
    id: 45,
    title: "liver masala",
    category: "mutton",
    price: 200,
    img: "./images/item-45.png",
    desc: `Spicy and flavorful mutton liver masala.`,
  },
  {
    id: 46,
    title: "liver fry",
    category: "mutton",
    price: 200,
    img: "./images/item-46.png",
    desc: `Fried mutton liver with a perfect balance of spices.`,
  },
  {
    id: 47,
    title: "brain fry",
    category: "mutton",
    price: 200,
    img: "./images/item-47.png",
    desc: `Deliciously spiced and fried mutton brain.`,
  },
  {
    id: 48,
    title: "brain masala",
    category: "mutton",
    price: 200,
    img: "./images/item-48.png",
    desc: `Mutton brain cooked in a flavorful and spicy masala sauce.`,
  },
  {
    id: 49,
    title: "brain pakoda",
    category: "mutton",
    price: 200,
    img: "./images/item-49.png",
    desc: `Crispy and tasty pakodas made with mutton brain.`,
  },
  {
    id: 50,
    title: "ginger fish",
    category: "seafood",
    price: 200,
    img: "./images/item-50.png",
    desc: `Fish cooked with ginger and spices for a delightful flavor.`,
  },
  {
    id: 51,
    title: "fish curry",
    category: "seafood",
    price: 200,
    img: "./images/item-51.png",
    desc: `Traditional fish curry made with a blend of aromatic spices.`,
  },
  {
    id: 52,
    title: "fish tikka masala",
    category: "seafood",
    price: 200,
    img: "./images/item-52.png",
    desc: `Tender fish tikka cooked in a rich and creamy masala sauce.`,
  },
  {
    id: 53,
    title: "ginger prawns",
    category: "seafood",
    price: 200,
    img: "./images/item-53.png",
    desc: `Prawns cooked with ginger and spices for a delicious flavor.`,
  },
  {
    id: 54,
    title: "prawns curry",
    category: "seafood",
    price: 200,
    img: "./images/item-54.png",
    desc: `Authentic prawns curry with a perfect blend of spices and flavors.`,
  },
  {
    id: 55,
    title: "prawns fry",
    category: "seafood",
    price: 200,
    img: "./images/item-55.png",
    desc: `Crispy and spicy fried prawns that are perfect as an appetizer.`,
  },
  {
    id: 56,
    title: "loose prawns",
    category: "seafood",
    price: 200,
    img: "./images/item-56.png",
    desc: `Tender and succulent prawns cooked in a delicious sauce.`,
  },
  {
    id: 57,
    title: "prawns pakoda",
    category: "seafood",
    price: 200,
    img: "./images/item-57.png",
    desc: `Crunchy and flavorful pakodas made with juicy prawns.`,
  },
  {
    id: 58,
    title: "chilly prawns",
    category: "seafood",
    price: 200,
    img: "./images/item-58.png",
    desc: `Spicy and tangy prawns stir-fried with peppers and spices.`,
  },
  {
    id: 59,
    title: "chilli fish",
    category: "seafood",
    price: 200,
    img: "./images/item-59.png",
    desc: `Fish cooked with peppers and spices for a fiery and flavorful dish.`,
  },
  {
    id: 60,
    title: "apollo fish",
    category: "seafood",
    price: 200,
    img: "./images/item-60.png",
    desc: `A popular Andhra-style fish preparation with a unique blend of spices.`,
  },
  {
    id: 61,
    title: "fish finger",
    category: "seafood",
    price: 200,
    img: "./images/item-61.png",
    desc: `Crispy and breaded fish fingers that make a perfect snack.`,
  },
  {
    id: 62,
    title: "fish 65",
    category: "seafood",
    price: 200,
    img: "./images/item-62.png",
    desc: `Spicy and tangy deep-fried fish, seasoned with aromatic spices.`,
  },
  {
    id: 63,
    title: "fish fry",
    category: "seafood",
    price: 200,
    img: "./images/item-63.png",
    desc: `Crispy and flavorful fried fish that is perfect as a main course.`,
  },
  {
    id: 64,
    title: "tandoori platter",
    category: "tandoori",
    price: 300,
    img: "./images/item-64.png",
    desc: `Assortment of tandoori delicacies including chicken, fish, and paneer.`,
  },
  {
    id: 65,
    title: "tandoori chicken",
    category: "tandoori",
    price: 300,
    img: "./images/item-65.png",
    desc: `Classic tandoori chicken marinated in yogurt and spices, grilled to perfection.`,
  },
  {
    id: 66,
    title: "tandoori chicken 1 pc",
    category: "tandoori",
    price: 300,
    img: "./images/item-66.png",
    desc: `Single piece of succulent tandoori chicken, marinated and grilled with care.`,
  },
  {
    id: 67,
    title: "tangdi 65",
    category: "tandoori",
    price: 300,
    img: "./images/item-67.png",
    desc: `Spicy and tangy grilled chicken drumsticks with a flavorful coating.`,
  },
  {
    id: 68,
    title: "chicken malai tikka",
    category: "tandoori",
    price: 300,
    img: "./images/item-68.png",
    desc: `Creamy and tender chicken tikka marinated in a rich malai (cream) sauce.`,
  },
  {
    id: 69,
    title: "garlic kebab",
    category: "tandoori",
    price: 300,
    img: "./images/item-69.png",
    desc: `Delicious and aromatic kebabs infused with the flavors of garlic.`,
  },
  {
    id: 70,
    title: "banjara kebab",
    category: "tandoori",
    price: 300,
    img: "./images/item-70.png",
    desc: `Spicy and succulent kebabs with a smoky flavor, inspired by traditional Banjara cuisine.`,
  },
  {
    id: 71,
    title: "chicken tikka",
    category: "tandoori",
    price: 300,
    img: "./images/item-71.png",
    desc: `Tender and flavorful boneless chicken pieces marinated and grilled to perfection.`,
  },
  {
    id: 72,
    title: "tangdi kebab",
    category: "tandoori",
    price: 300,
    img: "./images/item-72.png",
    desc: `Grilled chicken drumsticks marinated in a flavorful blend of spices.`,
  },
  {
    id: 73,
    title: "tangdi kebab 1 pc",
    category: "tandoori",
    price: 300,
    img: "./images/item-73.png",
    desc: `Individual chicken drumstick kebab, perfectly seasoned and grilled.`,
  },
  {
    id: 74,
    title: "fish tikka",
    category: "tandoori",
    price: 300,
    img: "./images/item-74.png",
    desc: `Deliciously marinated and grilled fish chunks with aromatic spices.`,
  },
  {
    id: 75,
    title: "paneer tikka",
    category: "tandoori",
    price: 300,
    img: "./images/item-75.png",
    desc: `Juicy and marinated paneer (cottage cheese) cubes grilled to perfection.`,
  },
  {
    id: 76,
    title: "paneer garlic tikka",
    category: "tandoori",
    price: 300,
    img: "./images/item-76.png",
    desc: `Paneer tikka infused with the flavors of garlic for a delightful twist.`,
  },
  {
    id: 77,
    title: "paneer ginger tikka",
    category: "tandoori",
    price: 300,
    img: "./images/item-77.png",
    desc: `Paneer tikka marinated with a zingy blend of ginger and spices.`,
  },
  {
    id: 78,
    title: "paneer malai tikka",
    category: "tandoori",
    price: 300,
    img: "./images/item-78.png",
    desc: `Creamy and succulent paneer tikka marinated in a rich malai (cream) sauce.`,
  },
  {
    id: 79,
    title: "egg spring roll",
    category: "egg",
    price: 180,
    img: "./images/item-79.png",
    desc: `Crispy spring rolls filled with delicious egg filling.`,
  },
  {
    id: 80,
    title: "special boiled egg",
    category: "egg",
    price: 180,
    img: "./images/item-80.png",
    desc: `Perfectly boiled eggs seasoned with special spices and flavors.`,
  },
  {
    id: 81,
    title: "boiled egg",
    category: "egg",
    price: 180,
    img: "./images/item-81.png",
    desc: `Simple and classic boiled eggs, a nutritious and filling snack.`,
  },
  {
    id: 82,
    title: "egg pakoda",
    category: "egg",
    price: 180,
    img: "./images/item-82.png",
    desc: `Crispy and spicy fritters made with egg and gram flour batter.`,
  },
  {
    id: 83,
    title: "egg burjee",
    category: "egg",
    price: 180,
    img: "./images/item-83.png",
    desc: `Scrambled eggs cooked with onions, tomatoes, and spices.`,
  },
  {
    id: 84,
    title: "omelette",
    category: "egg",
    price: 180,
    img: "./images/item-84.png",
    desc: `Classic omelette made with beaten eggs and a choice of fillings.`,
  },
  {
    id: 85,
    title: "half fry",
    category: "egg",
    price: 180,
    img: "./images/item-85.png",
    desc: `Eggs fried with a runny yolk, perfect for dipping with toast.`,
  },
  {
    id: 86,
    title: "egg 65",
    category: "egg",
    price: 180,
    img: "./images/item-86.png",
    desc: `Spicy and tangy deep-fried eggs, seasoned with aromatic spices.`,
  },
  {
    id: 87,
    title: "egg manchuria",
    category: "egg",
    price: 180,
    img: "./images/item-87.png",
    desc: `Indo-Chinese style egg fritters cooked in a tangy and spicy sauce.`,
  },
  {
    id: 88,
    title: "egg chilly",
    category: "egg",
    price: 180,
    img: "./images/item-88.png",
    desc: `Eggs cooked with onions, bell peppers, and spices for a flavorful dish.`,
  },
  {
    id: 89,
    title: "egg curry",
    category: "egg",
    price: 180,
    img: "./images/item-89.png",
    desc: `Aromatic and rich curry made with boiled eggs in a spiced tomato-based gravy.`,
  },
  {
    id: 90,
    title: "phulka",
    category: "roti",
    price: 50,
    img: "./images/item-90.png",
    desc: `Thin and soft Indian bread made from whole wheat flour.`,
  },
  {
    id: 91,
    title: "chapati",
    category: "roti",
    price: 50,
    img: "./images/item-91.png",
    desc: `Thin unleavened bread made from whole wheat flour, a staple in Indian cuisine.`,
  },
  {
    id: 92,
    title: "roti",
    category: "roti",
    price: 50,
    img: "./images/item-92.png",
    desc: `Round and wholesome bread made from whole wheat flour.`,
  },
  {
    id: 93,
    title: "naan",
    category: "roti",
    price: 50,
    img: "./images/item-93.png",
    desc: `Soft and fluffy leavened bread, typically cooked in a tandoor (clay oven).`,
  },
  {
    id: 94,
    title: "butter naan",
    category: "roti",
    price: 50,
    img: "./images/item-94.png",
    desc: `Naan bread topped with melted butter for a rich and flavorful taste.`,
  },
  {
    id: 95,
    title: "tandoor paratha",
    category: "roti",
    price: 50,
    img: "./images/item-95.png",
    desc: `Flaky and layered bread cooked in a tandoor for a delightful texture.`,
  },
  {
    id: 96,
    title: "ghee roti",
    category: "roti",
    price: 50,
    img: "./images/item-96.png",
    desc: `Roti made with clarified butter (ghee) for a rich and aromatic flavor.`,
  },
  {
    id: 97,
    title: "ghee chapati",
    category: "roti",
    price: 50,
    img: "./images/item-97.png",
    desc: `Chapati made with clarified butter (ghee) for a delicious and indulgent taste.`,
  },
  {
    id: 98,
    title: "oil paratha",
    category: "roti",
    price: 50,
    img: "./images/item-98.png",
    desc: `Paratha made with oil for a softer and flakier texture.`,
  },
  {
    id: 99,
    title: "aloo paratha",
    category: "roti",
    price: 50,
    img: "./images/item-99.png",
    desc: `Flavorful paratha stuffed with a spiced potato filling.`,
  },
  {
    id: 100,
    title: "gobi paratha",
    category: "roti",
    price: 50,
    img: "./images/item-100.png",
    desc: `Paratha filled with a delicious spiced cauliflower (gobi) mixture.`,
  },
  {
    id: 101,
    title: "pudina paratha",
    category: "roti",
    price: 50,
    img: "./images/item-101.png",
    desc: `Paratha flavored with fresh mint leaves for a refreshing taste.`,
  },
  {
    id: 102,
    title: "paneer paratha",
    category: "roti",
    price: 50,
    img: "./images/item-102.png",
    desc: `Paratha stuffed with a flavorful cottage cheese (paneer) filling.`,
  },
  {
    id: 103,
    title: "kheema naan",
    category: "roti",
    price: 50,
    img: "./images/item-103.png",
    desc: `Naan bread filled with a delicious minced meat (kheema) mixture.`,
  },
  {
    id: 104,
    title: "paneer butter masala",
    category: "veg",
    price: 200,
    img: "./images/item-104.png",
    desc: `Soft and creamy paneer (cottage cheese) cooked in a rich and buttery tomato-based gravy.`,
  },
  {
    id: 105,
    title: "palak paneer",
    category: "veg",
    price: 200,
    img: "./images/item-105.png",
    desc: `Paneer (cottage cheese) cooked with spinach in a flavorful and nutritious gravy.`,
  },
  {
    id: 106,
    title: "paneer tikka masala",
    category: "veg",
    price: 200,
    img: "./images/item-106.png",
    desc: `Grilled paneer (cottage cheese) cubes cooked in a creamy and spicy tomato-based sauce.`,
  },
  {
    id: 107,
    title: "ginger paneer",
    category: "veg",
    price: 200,
    img: "./images/item-107.png",
    desc: `Paneer (cottage cheese) cooked with ginger and spices for a delightful flavor.`,
  },
  {
    id: 108,
    title: "kaju paneer",
    category: "veg",
    price: 200,
    img: "./images/item-108.png",
    desc: `Paneer (cottage cheese) cooked with cashews and a blend of aromatic spices.`,
  },
  {
    id: 109,
    title: "veg malai kofta",
    category: "veg",
    price: 200,
    img: "./images/item-109.png",
    desc: `Soft and creamy vegetable dumplings served in a rich and creamy gravy.`,
  },
  {
    id: 110,
    title: "mixed veg curry",
    category: "veg",
    price: 200,
    img: "./images/item-110.png",
    desc: `Assorted vegetables cooked in a flavorful and spiced curry sauce.`,
  },
  {
    id: 111,
    title: "aloo mutter",
    category: "veg",
    price: 200,
    img: "./images/item-111.png",
    desc: `A classic Indian dish made with potatoes (aloo) and peas (mutter) in a spiced gravy.`,
  },
  {
    id: 112,
    title: "ginger veg",
    category: "veg",
    price: 200,
    img: "./images/item-112.png",
    desc: `Mixed vegetables cooked with ginger and spices for a flavorful and aromatic dish.`,
  },
  {
    id: 113,
    title: "gobi masala",
    category: "veg",
    price: 200,
    img: "./images/item-113.png",
    desc: `Cauliflower florets cooked in a spicy and flavorful masala sauce.`,
  },
  {
    id: 114,
    title: "paneer burjee",
    category: "veg",
    price: 200,
    img: "./images/item-114.png",
    desc: `Scrambled paneer (cottage cheese) cooked with onions, tomatoes, and spices.`,
  },
  {
    id: 115,
    title: "dal makhani",
    category: "veg",
    price: 200,
    img: "./images/item-115.png",
    desc: `A rich and creamy lentil dish made with black lentils, kidney beans, and aromatic spices.`,
  },
  {
    id: 116,
    title: "dal fry",
    category: "veg",
    price: 200,
    img: "./images/item-116.png",
    desc: `Tempting and flavorful lentil dish made with lentils, onions, tomatoes, and spices.`,
  },
  {
    id: 117,
    title: "stuffed tomato",
    category: "veg",
    price: 200,
    img: "./images/item-117.png",
    desc: `Tomato stuffed with a delicious filling of spices, vegetables, and paneer.`,
  },
  {
    id: 118,
    title: "aloo palak",
    category: "veg",
    price: 200,
    img: "./images/item-118.png",
    desc: `Potatoes (aloo) cooked with spinach (palak) in a flavorful and nutritious gravy.`,
  },
  {
    id: 119,
    title: "plain palak",
    category: "veg",
    price: 200,
    img: "./images/item-119.png",
    desc: `A simple and nutritious dish made with spinach (palak) cooked with mild spices.`,
  },
  {
    id: 120,
    title: "mixed raita",
    category: "veg",
    price: 200,
    img: "./item-120.png",
    desc: `Refreshing yogurt-based side dish with a mix of diced vegetables and spices.`,
  },
  {
    id: 121,
    title: "curd",
    category: "veg",
    price: 200,
    img: "./item-121.png",
    desc: `Plain yogurt, a cooling and nutritious accompaniment to any meal.`,
  },
  {
    id: 122,
    title: "chicken biryani",
    category: "biryani",
    price: 300,
    img: "./item-122.png",
    desc: `Aromatic and flavorful rice dish cooked with succulent chicken pieces and fragrant spices.`,
  },
  {
    id: 123,
    title: "mutton dum biryani",
    category: "biryani",
    price: 300,
    img: "./item-123.png",
    desc: `Traditional dum-style biryani made with tender mutton, fragrant rice, and aromatic spices.`,
  },
  {
    id: 124,
    title: "special chicken biryani",
    category: "biryani",
    price: 300,
    img: "./item-124.png",
    desc: `Exquisite and flavorful chicken biryani prepared with special spices and premium ingredients.`,
  },
  {
    id: 125,
    title: "chicken tikka biryani",
    category: "biryani",
    price: 300,
    img: "./item-125.png",
    desc: `Delicious biryani made with marinated and grilled chicken tikka, layered with fragrant rice.`,
  },
  {
    id: 126,
    title: "special mutton biryani",
    category: "biryani",
    price: 300,
    img: "./item-126.png",
    desc: `Delectable mutton biryani prepared with special spices, tender meat, and fragrant rice.`,
  },
  {
    id: 127,
    title: "kheema biryani",
    category: "biryani",
    price: 300,
    img: "./item-127.png",
    desc: `Flavorful biryani made with spiced minced meat (kheema) and aromatic rice.`,
  },
  {
    id: 128,
    title: "prawns biryani",
    category: "biryani",
    price: 300,
    img: "./item-128.png",
    desc: `Irresistible biryani prepared with succulent prawns, fragrant rice, and aromatic spices.`,
  },
  {
    id: 129,
    title: "fish biryani",
    category: "biryani",
    price: 300,
    img: "./item-129.png",
    desc: `Delicious biryani made with flavorful fish pieces, fragrant rice, and aromatic spices.`,
  },
  {
    id: 130,
    title: "egg biryani",
    category: "biryani",
    price: 300,
    img: "./item-130.png",
    desc: `Scrumptious biryani made with hard-boiled eggs, fragrant rice, and a blend of spices.`,
  },
  {
    id: 131,
    title: "special fish biryani",
    category: "biryani",
    price: 300,
    img: "./item-131.png",
    desc: `Exquisite biryani made with special fish pieces, fragrant rice, and a flavorful spice mix.`,
  },
  {
    id: 132,
    title: "mixed fried rice",
    category: "biryani",
    price: 300,
    img: "./item-132.png",
    desc: `Assorted vegetables and rice stir-fried with spices for a delicious and satisfying meal.`,
  },
  {
    id: 133,
    title: "chicken fried rice",
    category: "biryani",
    price: 300,
    img: "./item-133.png",
    desc: `Classic fried rice made with tender chicken pieces, mixed vegetables, and aromatic spices.`,
  },
  {
    id: 134,
    title: "paneer tikka biryani",
    category: "biryani",
    price: 300,
    img: "./item-134.png",
    desc: `Flavorful biryani made with marinated paneer tikka, fragrant rice, and a blend of spices.`,
  },
  {
    id: 135,
    title: "veg biryani",
    category: "biryani",
    price: 300,
    img: "./item-135.png",
    desc: `Delicious biryani made with assorted vegetables, fragrant rice, and a blend of aromatic spices.`,
  },
  {
    id: 136,
    title: "veg pulao",
    category: "biryani",
    price: 300,
    img: "./item-136.png",
    desc: `Flavorful rice dish cooked with a mix of vegetables, fragrant spices, and aromatic herbs.`,
  },
  {
    id: 137,
    title: "biryani rice",
    category: "biryani",
    price: 300,
    img: "./item-137.png",
    desc: `Fragrant and long-grain rice used as the base for various biryani dishes.`,
  },
  {
    id: 138,
    title: "jeera rice",
    category: "biryani",
    price: 300,
    img: "./item-138.png",
    desc: `Basmati rice cooked with cumin seeds, giving it a distinct and aromatic flavor.`,
  },
  {
    id: 139,
    title: "palak rice",
    category: "biryani",
    price: 300,
    img: "./item-139.png",
    desc: `Rice cooked with spinach (palak), resulting in a vibrant and nutritious dish.`,
  },
  {
    id: 140,
    title: "dal rice",
    category: "biryani",
    price: 300,
    img: "./item-140.png",
    desc: `Combination of lentils (dal) and rice, a comforting and wholesome meal.`,
  },
  {
    id: 141,
    title: "curd rice",
    category: "biryani",
    price: 300,
    img: "./item-141.png",
    desc: `Rice mixed with yogurt (curd), tempered with spices and often accompanied by pickles.`,
  },
  {
    id: 142,
    title: "steamed rice",
    category: "biryani",
    price: 300,
    img: "./item-142.png",
    desc: `Simple and plain boiled rice, a versatile accompaniment to many dishes.`,
  },
  {
    id: 143,
    title: "veg fried rice",
    category: "biryani",
    price: 300,
    img: "./item-143.png",
    desc: `Flavorful fried rice made with assorted vegetables, aromatic spices, and a touch of soy sauce.`,
  },
  {
    id: 144,
    title: "paneer fried rice",
    category: "biryani",
    price: 300,
    img: "./item-144.png",
    desc: `Delicious fried rice made with paneer (cottage cheese), mixed vegetables, and aromatic spices.`,
  },

];

const sectionCenter = document.querySelector(".section-center");
const container = document.querySelector(".btn-container");

// load items 
window.addEventListener("DOMContentLoaded", function() {
  displayMenuItems(menu);
  displayMenuButtons();
});


function displayMenuItems(menuItems){
  let displayMenu = menuItems.map(function (item) {
    // console.log(item);

    return `<article class="menu-item">
    <img src=${item.img} class="photo" alt=${item.title}>
    <div class="item-info">
      <header>
        <h4>${item.title}</h4>
        <h4 class="price">${item.price}</h4>
      </header>
      <p class="item-text">
        ${item.desc}
      </p>
    </div>
  </article>`;
  });
  displayMenu = displayMenu.join("");
  sectionCenter.innerHTML = displayMenu;
} 

function displayMenuButtons() {
  const categories = menu.reduce(function (values, item) {
    if(!values.includes(item.category)) {
      values.push(item.category);
    }
    return values;
  },
  ['all']
  );
const categoryBtns = categories.map(function(category) {
   return `<button class="filter-btn" type="button"
    data-id=${category}>
            ${category}
          </button>`
}).join("");  
container.innerHTML = categoryBtns;
const filterBtns = container.querySelectorAll(".filter-btn");
// filter items 
filterBtns.forEach(function (btn) {
  btn.addEventListener("click", function(e) {

    const category = e.currentTarget.dataset.id;
    const menuCategory = menu.filter(function (menuItem) {
      // console.log(menuItems.category);
      if(menuItem.category === category){
        return menuItem;
      }
    });
    //console.log(menuCategory);
    if(category === "all") {
      displayMenuItems(menu);
    }else {
      displayMenuItems(menuCategory);
    }
  });
});
}